dist: xenial # Ubuntu 16.04

language: node_js

node_js:
  - "node"
  - "10.15.0"

branches: # 指定分支提交时才会运行travis ci
  only:
  - dev

before_install:
  - npm install -g hexo-cli

install:
  - cd ./blogs/
  - npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
  - git config --global user.name $USER_NAME
  - git config --global user.email $USER_EMAIL
# - git clone git://github.com/heroicyang/hexo-theme-modernist.git themes/modernist

script:
  - pwd
  - hexo clean
  - hexo generate

after_success:
  - cd ./blogs/
  - sed -i'' "s~https://github.com/zjZSTU/Hexo-Travis-CI-Test.git~https://${GITHUB_REPO_TOKEN}@github.com/zjZSTU/Hexo-Travis-CI-Test.git~" _config.yml
  - hexo deploy

# deploy:
#   local-dir: ./blogs/public
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_REPO_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   target-branch: master
#   on:
#     branch: dev